collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9457573
  brandStrength: 0.7620838
  lightness: 0.7835661
  brandColors:
    - '#3B3738'
    - '#017AAA'
    - '#D7D7D7'
    - '#99AAB4'
    - '#BDFFFF'
  rhythmicContrast: 1
typography_spectrum: 0.6933405
layout_spectrum: 0.8233083
name: CausEffect
